export const FETCH_BIBLES_REQUEST = 'FETCH_BIBLE_REQUEST'
export const FETCH_BIBLE_SUCCESS = 'FETCH_BIBLE_SUCCESS'
export const FETCH_BIBLE_FAILURE = 'FETCH_BIBLE_FAILURE'

export const SELECT_BIBLE_REQUEST = 'SELECT_BIBLE_REQUEST'
export const SELECT_BIBLE_SUCCESS = 'SELECT_BIBLE_SUCCESS'
export const SELECT_BIBLE_FAILURE = 'SELECT_BIBLE_FAILURE'
